### ISSUE TITLE
Allow users to disable stdout

### ISSUE THREAD

**Issue by amclay** [cdipaolo/goml#18]
It would be appreciated if there was a global flag to disable logging to standard out. When creating models, it's not always wanted to fill screen space with the model output.

Alternatively it'd be nice if instead of default printing, you could call a method that would give you the variables, like

`model.OptimzationMethod() -> "Batch Gradient Ascent`
`model.TrainingExamples() -> 4000`

or return a struct with all the information, so that callers can decide what and where they want to print that information.

**Comment by piazzamp** [comment]
I think the best practice is to allow package consumers to use their own logger. iirc, this is implemented in some of the models but I'll dig deeper when I get a few moments.
