### ISSUE TITLE
Any interest in XGBoost?

### ISSUE THREAD

**Issue by amlocek** [cdipaolo/goml#26]
Hello,
I have an experimental high performance XGBoost (tree_method=exact only) implementation here:

https://github.com/Statfactory/cortado (python + llvm)
https://github.com/Statfactory/cortado-fs (F#)
https://github.com/Statfactory/JuML.jl (Julia)

I could port it to golang with some help if there is interest:)

Adam

**Comment by piazzamp** [comment]
if you want to publish a go implementation of your own, I'd be happy to link out to it in the readme, but I think one of the goals of this project is to be super self contained and simple
