### ISSUE TITLE
Bug in k nearest neighbors

### ISSUE THREAD

**Issue by thedadams** [cdipaolo/goml#4]
In the `Predict` function in `knn.go` you "initialize" the `neighbors` array with random elements from `k.trainingSet` and then use `insertSorted` to insert new data into the `neighbors` array.

This is a problem because `insertSorted` requires that the array you are inserting into be sorted; it uses binary search.  The random data you initialize the `neighbors` vector with may not sorted.

A possible fix is to get rid of the `rand` package altogether, initialize the `neighbors` vector with the first `k.K` elements from `k.trainingSet`, and sort `neighbors` before calculating the nearest neighbors.

I can submit a pull request if you like.

**Comment by cdipaolo** [comment]
Looking into it right now. Should have it fixed within the hour.

Thanks for the catch!
